import random

monsters = {
    "1/4": ["Aarakocra Skirmisher", "Animated Broom", "Animated Flying Sword", "Axe Beak", "Blink Dog",
            "Boar", "Bullywug Warrior", "Constrictor Snake", "Draft Horse", "Dretch", "Elk",
            "Giant Badger", "Giant Bat", "Giant Centipede", "Giant Frog", "Giant Lizard", "Giant Owl",
            "Giant Venomous Snake", "Giant Wolf Spider", "Goblin Warrior", "Grimlock", "Kenku",
            "Kuo-toa", "Modron Duodrone", "Mud Mephit", "Needle Blight", "Panther", "Pixie",
            "Priest Acolyte", "Pseudodragon", "Pteranodon", "Riding Horse", "Skeleton", "Smoke Mephit",
            "Sprite", "Steam Mephit", "Swarm Of Bats", "Swarm Of Rats", "Swarm Of Ravens",
            "Troglodyte", "Violet Fungus", "Winged Kobold", "Wolf", "Zombie"],
    "1/2": ["Ape", "Black Bear", "Cockatrice", "Crocodile", "Darkmantle", "Dust Mephit",
            "Gas Spore Fungus", "Giant Goat", "Giant Wasp", "Gnoll Warrior", "Gray Ooze",
            "Hobgoblin Warrior", "Ice Mephit", "Jackalwere", "Magma Mephit", "Magmin", "Modron Tridrone",
            "Myconid Adult", "Perfomer", "Piercer", "Rust Monster", "Sahuagin Warrior", "Satyr",
            "Scout", "Shadow", "Swarm Of Insects", "Tough", "Troll Limb", "Vine Blight", "Warhorse",
            "Warhorse Skeleton", "Worg"],
    "1": ["Animated Armor", "Brass Dragon Wyrmling", "Brown Bear", "Bugbear Warrior", "Copper Dragon Wyrmling",
          "Death Dog", "Dire Wolf", "Dryad", "Empyrean Iota", "Faerie Dragon Youth", "Ghoul", "Giant Eagle",
          "Giant Hyena", "Giant Spider", "Giant Toad", "Giant Vulture", "Goblin Boss", "Harpy",
          "Hippogriff", "Imp", "Kuo-toa Whip", "Lacedon Ghoul", "Lion", "Manes Vaporspawn",
          "Modron Quadrone", "Myconid Spore Servant", "Ogrillon Ogre", "Pirate", "Psychic Gray Ooze",
          "Quasit", "Salamander Fire Snake", "Scarecrow", "Specter", "Sphinx Of Wonder", "Spy",
          "Swarm Of Larvae", "Thri-kreen Marauder", "Tiger", "Yuan-ti Infiltrator"],
    "2": ["Allosaurus", "Animated Rug Of Smothering", "Ankheg", "Awakened Tree", "Azer Sentinel",
          "Bandit Captain", "Berserker", "Black Dragon Wyrmling", "Bronze Dragon Wyrmling", "Bulette Pup",
          "Carrion Crawler", "Centaur Trooper", "Cultist Fanatic", "Druid", "Ettercap",
          "Faerie Dragon Adult", "Gargoyle", "Gelatinous Cube", "Ghast", "Giant Boar",
          "Giant Constrictor Snake", "Giant Elk", "Gibbering Mouther", "Githzerai Monk", "Gnoll Pack Lord",
          "Green Dragon Wyrmling", "Grick", "Griffon", "Intellect Devourer", "Lizardfolk Geomancer",
          "Mage Apprentice", "Merrow", "Mimic", "Minotaur Skeleton", "Modron Pentadrone", "Myconid Sovereign",
          "Nothic", "Ochre Jelly", "Ogre", "Ogre Zombie", "Pegasus", "Peryton", "Plesiosaurus", "Polar Bear",
          "Poltergeist", "Priest", "Quaggoth", "Rhinoceros", "Saber-Toothed Tiger", "Sahuagin Priest",
          "Sea Hag", "Silver Dragon Wyrmling", "Spined Devil", "Swarm Of Stirgest", "Swarm Of Venomous Snakes",
          "Wererat", "White Dragon Wyrmling", "Will-o'-Wisp"],
    "3": ["Ankylosaurus", "Basilisk", "Bearded Devil", "Blue Dragon Wyrmling", "Bugbear Stalker", "Displacer Beast",
          "Doppelganger", "Flaming Skeleton", "Giant Scorpion", "Githyanki Soldier", "Goblin Hexer",
          "Golden Dragon Wyrmling", "Green Hag", "Grell", "Hell Hound", "Hobgoblin Captain", "Hook Horror",
          "Knight", "Kuo-toa Monitor", "Manticore", "Minotaur Of Baphomet", "Mummy", "Nightmare", "Owlbear",
          "Phase Spider", "Quaggoth Thonot", "Scout Captain", "Spectator", "Swarm Of Crawling Claws",
          "Swarm Of Lemures", "Vampire Familiar", "Warrior Veteran", "Werewolf", "Wight", "Winter Wolf",
          "Yeti", "Yuan-ti Malison"],
    "4": ["Aarakocra Aeromancer", "Archelon", "Banshee", "Black Pudding", "Bone Naga", "Bullywug Bog Sage",
          "Chuul", "Couatl", "Elephant", "Ettin", "Flameskull", "Ghost", "Gnoll Fang Of Yeenoghu",
          "Guard Captain", "Helmed Horror", "Hippopotamus", "Incubus", "Juvenile Shadow Dragon", "Lamia",
          "Lizardfolk Sovereign", "Red Dragon Wyrmling", "Shadow Demon", "Succubus", "Swarm Of Dretches",
          "Tough Boss", "Wereboar", "Weretiger"],
    "5": ["Air Elemental", "Barded Devil", "Barlgura", "Beholder Zombie", "Bulette", "Cambion", "Earth Elemental",
          "Fire Elemental", "Flesh Golem", "Giant Axe Beak", "Giant Crocodile", "Gladiator", "Gorgon",
          "Half-Dragon", "Hill Giant", "Mezzoloth", "Night Hag", "Otyugh", "Pixie Wonderbringer", "Red Slaad",
          "Revenant", "Roper", "Sahuagin Baron", "Salamander", "Shambling Mound", "Triceratops", "Troll",
          "Umber Hulk", "Unicorn", "Vampire Spawn", "Water Elemental", "Werebear", "Wraith", "Xorn",
          "Young Remorhaz"],
    "6": ["Azer Pyromancer", "Chasme", "Chimera", "Cyclops Sentry", "Drider", "Galeb Duhr", "Ghast Gravecaller",
          "Githzerai Zerth", "Hobgoblin Warlord", "Invisible Stalker", "Kuo-toa Archpriest", "Mage", "Mammoth",
          "Medusa", "Merfolk Wavebender", "Performer Maestro", "Pirate Captain", "Satyr Revelmaster", "Vrock",
          "Wyvern", "Young Brass Dragon", "Young White Dragon"],
    "7": ["Bandit Deceiver", "Blue Slaad", "Centaur Warden", "Giant Ape", "Graveyard Revenant", "Grick Ancient",
          "Mind Flayer", "Oni", "Primeval Owlbear", "Shield Guardian", "Stone Giant", "Tree Blight",
          "Violet Fungus Necrohulk", "Young Black Dragon", "Young Copper Dragon", "Yuan-ti Abomination"],
    "8": ["Aberrant Cultist", "Assassin", "Berserker Commander", "Chain Devil", "Cloaker", "Cockatrice Regent",
          "Death Cultist", "Elemental Cultist", "Fiend Cultist", "Fomorian", "Frost Giant", "Githyanki Knight",
          "Gnoll Demoniac", "Green Slaad", "Hezrou", "Hydra", "Sphinx Of Secrets", "Spirit Naga",
          "Thri-kreen Psion", "Tyrannosaurus Rex", "Vampire Nightbringer", "Young Bronze Dragon",
          "Young Green Dragon"],
    "9": ["Abominable Yeti", "Bone Devil", "Brazen Gorgon", "Clay Golem", "Cloud Giant", "Fire Giant",
          "Glabrezu", "Gray Slaad", "Nycaloth", "Treant", "Young Blue Dragon", "Young Silver Dragon"],
    "10": ["Aboleth", "Cultist Hierophant", "Cyclops Oracle", "Death Slaad", "Deva", "Dire Worg",
           "Guardian Naga", "Haunting Revenant", "Noble Prodigy", "Performer Legend", "Spy Master",
           "Stone Golem", "Warrior Commander", "Yochlol", "Young Gold Dragon", "Young Red Dragon"],
    "11": ["Bandit Crime Lord", "Behir", "Dao", "Death Knight Aspirant", "Djinni", "Efreeti",
           "Horned Devil", "Marid", "Mind Flayer Arcanist", "Remorhaz", "Roc", "Sphinx Of Lore"],
    "12": ["Arcanaloth", "Archmage", "Archpriest", "Erinyes", "Githzerai Psion", "Pirate Admiral",
           "Questing Knight"],
    "13": ["Adult Brass Dragon", "Adult White Dragon", "Beholder", "Nalfeshnee", "Rakshasa",
           "Shadow Dragon", "Storm Giant", "Ultroloth", "Vampire"],
    "14": ["Adult Black Dragon", "Adult Copper Dragon", "Death Tyrant", "Ice Devil"],
    "15": ["Adult Bronze Dragon", "Adult Green Dragon", "Mummy Lord", "Purple Worm",
           "Salamander Inferno Master", "Vampire Umbral Lord"],
    "16": ["Adult Blue Dragon", "Adult Silver Dragon", "Githyanki Dracomancer", "Gulthias Blight",
           "Iron Golem", "Marilith", "Planetar"],
    "17": ["Adult Gold Dragon", "Adult Red Dragon", "Death Knight", "Dracolich", "Dragon Turtle",
           "Goristro", "Sphinx Of Valor"],
    "18": ["Demilich"],
    "19": ["Balor"],
    "20": ["Ancient Brass Dragon", "Ancient White Dragon", "Animal Lord", "Pit Fiend"],
    "21": ["Ancient Black Dragon", "Ancient Copper Dragon", "Arch-hag", "Lich", "Solar"],
    "22": ["Ancient Bronze Dragon", "Ancient Green Dragon", "Elemental Cataclysm"],
    "23": ["Ancient Blue Dragon", "Ancient Silver Dragon", "Blob Of Annihilation", "Empyrean",
           "Kraken"],
    "24": ["Ancient Gold Dragon", "Ancient Red Dragon"],
}

spells = {
    "cantrip": [
        {"name": "Acid Splash", "school": "Evocation"},
        {"name": "Blade Ward", "school": "Abjuration"},
        {"name": "Chill Touch", "school": "Necromancy"},
        {"name": "Eldritch Blast", "school": "Evocation"},
        {"name": "Fire Bolt", "school": "Evocation"},
        {"name": "Guidance", "school": "Divination"},
        {"name": "Light", "school": "Evocation"},
        {"name": "Mage Hand", "school": "Conjuration"},
        {"name": "Mending", "school": "Transmutation"},
        {"name": "Mind Sliver", "school": "Enchantment"},
        {"name": "Poison Spray", "school": "Necromancy"},
        {"name": "Produce Flame", "school": "Conjuration"},
        {"name": "Ray Of Frost", "school": "Evocation"},
        {"name": "Resistance", "school": "Abjuration"},
        {"name": "Sacred Flame", "school": "Evocation"},
        {"name": "Shillelagh", "school": "Transmutation"},
        {"name": "Shocking Grasp", "school": "Evocation"},
        {"name": "Sorcerous Burst", "school": "Evocation"},
        {"name": "Spare The Dying", "school": "Necromancy"},
        {"name": "Starry Wisp", "school": "Evocation"},
        {"name": "Thorn Whip", "school": "Transmutation"},
        {"name": "Thunderclap", "school": "Evocation"},
        {"name": "Toll The Dead", "school": "Necromancy"},
        {"name": "True Strike", "school": "Divination"},
        {"name": "Vicious Mockery", "school": "Enchantment"},
        {"name": "Word Of Radiance", "school": "Evocation"},
    ],
    "level 1": [
        {"name": "Armor Of Agathys", "school": "Abjuration"},
        {"name": "Arms Of Hadar", "school": "Conjuration"},
        {"name": "Bane", "school": "Enchantment"},
        {"name": "Bless", "school": "Enchantment"},
        {"name": "Burning Hands", "school": "Evocation"},
        {"name": "Charm Person", "school": "Enchantment"},
        {"name": "Chromatic Orb", "school": "Evocation"},
        {"name": "Color Spray", "school": "Illusion"},
        {"name": "Command", "school": "Enchantment"},
        {"name": "Compelled Duel", "school": "Enchantment"},
        {"name": "Cure Wounds", "school": "Abjuration"},
        {"name": "Detect Evil And Good", "school": "Divination"},
        {"name": "Detect Magic", "school": "Divination"},
        {"name": "Dissonant Whispers", "school": "Enchantment"},
        {"name": "Divine Favor", "school": "Transmutation"},
        {"name": "Divine Smite", "school": "Evocation"},
        {"name": "Ensnaring Strike", "school": "Conjuration"},
        {"name": "Entangle", "school": "Conjuration"},
        {"name": "Expeditious Retreat", "school": "Transmutation"},
        {"name": "Faerie Fire", "school": "Evocation"},
        {"name": "False Life", "school": "Necromancy"},
        {"name": "Feather Fall", "school": "Transmutation"},
        {"name": "Find Familiar", "school": "Conjuration"},
        {"name": "Fog Cloud", "school": "Conjuration"},
        {"name": "Goodberry", "school": "Conjuration"},
        {"name": "Grease", "school": "Conjuration"},
        {"name": "Guiding Bolt", "school": "Evocation"},
        {"name": "Hail Of Throns", "school": "Conjuration"},
        {"name": "Healing Word", "school": "Abjuration"},
        {"name": "Hellish Rebuke", "school": "Evocation"},
        {"name": "Heroism", "school": "Enchantment"},
        {"name": "Hex", "school": "Enchantment"},
        {"name": "Hunter's Mark", "school": "Divination"},
        {"name": "Ice Knife", "school": "Conjuration"},
        {"name": "Inflict Wounds", "school": "Necromancy"},
        {"name": "Jump", "school": "Transmutation"},
        {"name": "Longstridedr", "school": "Transmutation"},
        {"name": "Mage Armor", "school": "Abjuration"},
        {"name": "Magic Missile", "school": "Evocation"},
        {"name": "Protection From Evil And Good", "school": "Abjuration"},
        {"name": "Ray Of Sickness", "school": "Necromancy"},
        {"name": "Sanctuary", "school": "Abjuration"},
        {"name": "Searing Smite", "school": "Evocation"},
        {"name": "Shield", "school": "Abjuration"},
        {"name": "Shield Of Faith", "school": "Abjuration"},
        {"name": "Sleep", "school": "Enchantment"},
        {"name": "Tasha's Hideous Laughter", "school": "Enchantment"},
        {"name": "Thunderous Smite", "school": "Evocation"},
        {"name": "Thunderwave", "school": "Evocation"},
        {"name": "With Bolt", "school": "Evocation"},
        {"name": "Wrathful Smite", "school": "Necromancy"},
    ],
    "level 2": [
        {"name": "Aid", "school": "Abjuration"},
        {"name": "Arcane Lock", "school": "Abjuration"},
        {"name": "Arcane Vigor", "school": "Abjuration"},
        {"name": "Barkskin", "school": "Transmutation"},
        {"name": "Blindness/Deafness", "school": "Transmutation"},
        {"name": "Blur", "school": "Illusion"},
        {"name": "Cloud Of Daggers", "school": "Conjuration"},
        {"name": "Continual Flame", "school": "Evocation"},
        {"name": "Cordon Of Arrows", "school": "Transmutation"},
        {"name": "Crown Of Madness", "school": "Enchantment"},
        {"name": "Darkness", "school": "Evocation"},
        {"name": "Dragon's Breath", "school": "Transmutation"},
        {"name": "Enchance Ability", "school": "Transmutation"},
        {"name": "Enlarge/Reduce", "school": "Transmutation"},
        {"name": "Find Steed", "school": "Conjuration"},
        {"name": "Flame Blade", "school": "Evocation"},
        {"name": "Flaming Sphere", "school": "Conjuration"},
        {"name": "Gust Of Wind", "school": "Evocation"},
        {"name": "Heat Metal", "school": "Transmutation"},
        {"name": "Hold Person", "school": "Enchantment"},
        {"name": "Invisibility", "school": "Illusion"},
        {"name": "Lesser Restoration", "school": "Abjuration"},
        {"name": "Levitate", "school": "Transmutation"},
        {"name": "Magic Weapon", "school": "Transmutation"},
        {"name": "Melf's Acid Arrow", "school": "Evocation"},
        {"name": "Mind Spike", "school": "Divination"},
        {"name": "Mirror Image", "school": "Illusion"},
        {"name": "Misty Step", "school": "Conjuration"},
        {"name": "Moonbeam", "school": "Evocation"},
        {"name": "Nystul's Magic Aura", "school": "Illusion"},
        {"name": "Phantasmal Force", "school": "Illusion"},
        {"name": "Prayer Of Healing", "school": "Abjuration"},
        {"name": "Protection From Poison", "school": "Abjuration"},
        {"name": "Ray Of Enfeeblement", "school": "Necromancy"},
        {"name": "Scorching Ray", "school": "Evocation"},
        {"name": "See Invisibility", "school": "Divination"},
        {"name": "Shatter", "school": "Evocation"},
        {"name": "Shining Smite", "school": "Transmutation"},
        {"name": "Silence", "school": "Illusion"},
        {"name": "Spider Climb", "school": "Transmutation"},
        {"name": "Spike Growth", "school": "Transmutation"},
        {"name": "Spiritual Weapon", "school": "Evocation"},
        {"name": "Summon Beast", "school": "Conjuration"},
        {"name": "Warding Bond", "school": "Abjuration"},
        {"name": "Web", "school": "Conjuration"},
    ],
    "level 3": [
        {"name": "Animate Dead", "school": "Necromancy"},
        {"name": "Aura Of Vitality", "school": "Abjuration"},
        {"name": "Beacon Of Hope", "school": "Abjuration"},
        {"name": "Bestow Curse", "school": "Necromancy"},
        {"name": "Blinding Smite", "school": "Evocation"},
        {"name": "Blink", "school": "Transmutation"},
        {"name": "Call Lightning", "school": "Conjuration"},
        {"name": "Conjure Animals", "school": "Conjuration"},
        {"name": "Conjure Barrage", "school": "Conjuration"},
        {"name": "Counterspell", "school": "Abjuration"},
        {"name": "Crusader's Mantle", "school": "Evocation"},
        {"name": "Daylight", "school": "Evocation"},
        {"name": "Dispel Magic", "school": "Abjuration"},
        {"name": "Elemental Weapon", "school": "Transmutation"},
        {"name": "Fear", "school": "Illusion"},
        {"name": "Feign Death", "school": "Necromancy"},
        {"name": "Fireball", "school": "Evocation"},
        {"name": "Fly", "school": "Transmutation"},
        {"name": "Gaseous Form", "school": "Transmutation"},
        {"name": "Glyph Of Warding", "school": "Abjuration"},
        {"name": "Haste", "school": "Transmutation"},
        {"name": "Hunger Of Hadar", "school": "Conjuration"},
        {"name": "Hypnotic Pattern", "school": "Illusion"},
        {"name": "Lightning Arrow", "school": "Transmutation"},
        {"name": "Lightning Bolt", "school": "Evocation"},
        {"name": "Magic Circle", "school": "Abjuration"},
        {"name": "Mass Healing Word", "school": "Abjuration"},
        {"name": "Meld Into Stone", "school": "Transmutation"},
        {"name": "Phantom Steed", "school": "Illusion"},
        {"name": "Plant Growth", "school": "Transmutation"},
        {"name": "Protection From Energy", "school": "Abjuration"},
        {"name": "Remove Curse", "school": "Abjuration"},
        {"name": "Revivify", "school": "Necromancy"},
        {"name": "Sleet Storm", "school": "Conjuration"},
        {"name": "Slow", "school": "Transmutation"},
        {"name": "Spirit Guardians", "school": "Conjuration"},
        {"name": "Stinking Cloud", "school": "Conjuration"},
        {"name": "Summon Fey", "school": "Conjuration"},
        {"name": "Summon Undead", "school": "Necromancy"},
        {"name": "Vampiric Touch", "school": "Necromancy"},
        {"name": "Wind Wall", "school": "Evocation"},
    ],
    "level 4": [
        {"name": "Aura Of Life", "school": "Abjuration"},
        {"name": "Aura Of Purity", "school": "Abjuration"},
        {"name": "Banishment", "school": "Abjuration"},
        {"name": "Blight", "school": "Necromancy"},
        {"name": "Charm Monster", "school": "Enchantment"},
        {"name": "Compulsion", "school": "Enchantment"},
        {"name": "Confusion", "school": "Enchantment"},
        {"name": "Conjure Minor Elementals", "school": "Conjuration"},
        {"name": "Conjure Woodlands Beings", "school": "Conjuration"},
        {"name": "Death Ward", "school": "Abjuration"},
        {"name": "Dimension Door", "school": "Conjuration"},
        {"name": "Dominate Beast", "school": "Enchantment"},
        {"name": "Evard's Black Tentacles", "school": "Conjuration"},
        {"name": "Fabricate", "school": "Transmutation"},
        {"name": "Fire Shield", "school": "Evocation"},
        {"name": "Fount Of Moonlight", "school": "Evocation"},
        {"name": "Freedom Of Movement", "school": "Abjuration"},
        {"name": "Gaint Insect", "school": "Conjuration"},
        {"name": "Grasping Vine", "school": "Conjuration"},
        {"name": "Greater Invisibility", "school": "Illusion"},
        {"name": "Guardian Of Faith", "school": "Conjuration"},
        {"name": "Hallucinatory Terrain", "school": "Illusion"},
        {"name": "Ice Storm", "school": "Evocation"},
        {"name": "Locate Creature", "school": "Divination"},
        {"name": "Mordenkainen's Faithful Hound", "school": "Conjuration"},
        {"name": "Otiluke's Resilient Sphere", "school": "Abjuration"},
        {"name": "Phantasmal Killer", "school": "Illusion"},
        {"name": "Polymorph", "school": "Transmutation"},
        {"name": "Staggering Smite", "school": "Enchantment"},
        {"name": "Stone Shape", "school": "Transmutation"},
        {"name": "Stoneskin", "school": "Transmutation"},
        {"name": "Summon Aberration", "school": "Conjuration"},
        {"name": "Summon Construct", "school": "Conjuration"},
        {"name": "Summon Elemental", "school": "Conjuration"},
        {"name": "Vitriolic Sphere", "school": "Evocation"},
        {"name": "Wall Of Fire", "school": "Evocation"},
    ],
    "level 5": [
        {"name": "Animate Objects", "school": "Transmutation"},
        {"name": "Antilife Shell", "school": "Abjuration"},
        {"name": "Awaken", "school": "Transmutation"},
        {"name": "Banishing Smite", "school": "Conjuration"},
        {"name": "Bigby's Hand", "school": "Evocation"},
        {"name": "Circle Of Power", "school": "Abjuration"},
        {"name": "Cloudkill", "school": "Conjuration"},
        {"name": "Cone Of Cold", "school": "Evocation"},
        {"name": "Conjure Elemental", "school": "Conjuration"},
        {"name": "Conjure Volley", "school": "Conjuration"},
        {"name": "Contagion", "school": "Necromancy"},
        {"name": "Creation", "school": "Illusion"},
        {"name": "Destructive Wave", "school": "Evocation"},
        {"name": "Dispel Evil And Good", "school": "Abjuration"},
        {"name": "Dominate Person", "school": "Enchantment"},
        {"name": "Flame Strike", "school": "Evocation"},
        {"name": "Geas", "school": "Enchantment"},
        {"name": "Greater Restoration", "school": "Abjuration"},
        {"name": "Hallow", "school": "Abjuration"},
        {"name": "Hold Monster", "school": "Enchantment"},
        {"name": "Insect Plague", "school": "Conjuration"},
        {"name": "Jallarzi's Storm Of Radiance", "school": "Evocation"},
        {"name": "Mass Cure Wounds", "school": "Abjuration"},
        {"name": "Mislead", "school": "Illusion"},
        {"name": "Passwall", "school": "Transmutation"},
        {"name": "Raise Dead", "school": "Necromancy"},
        {"name": "Reincarnate", "school": "Necromancy"},
        {"name": "Steel Wind Strike", "school": "Conjuration"},
        {"name": "Summon Celestial", "school": "Conjuration"},
        {"name": "Summon Dragon", "school": "Conjuration"},
        {"name": "Swift Quiver", "school": "Transmutation"},
        {"name": "Synaptic Static", "school": "Enchantment"},
        {"name": "Telekinesis", "school": "Transmutation"},
        {"name": "Tree Stride", "school": "Conjuration"},
        {"name": "Wall Of Force", "school": "Evocation"},
        {"name": "Wall Of Stone", "school": "Evocation"},
        {"name": "Yolande's Regal Presence", "school": "Enchantment"},
    ],
    "level 6": [
        {"name": "Arcane Gate", "school": "Conjuration"},
        {"name": "Blade Barrier", "school": "Evocation"},
        {"name": "Chain Lightning", "school": "Evocation"},
        {"name": "Circle Of Death", "school": "Necromancy"},
        {"name": "Conjure Fey", "school": "Conjuration"},
        {"name": "Contingency", "school": "Abjuration"},
        {"name": "Create Undead", "school": "Necromancy"},
        {"name": "Disintegrate", "school": "Transmutation"},
        {"name": "Eyebite", "school": "Necromancy"},
        {"name": "Flesh To Stone", "school": "Transmutation"},
        {"name": "Globe Of Invulnerability", "school": "Abjuration"},
        {"name": "Harm", "school": "Necromancy"},
        {"name": "Heal", "school": "Abjuration"},
        {"name": "Heroe's Feast", "school": "Conjuration"},
        {"name": "Move Earth", "school": "Transmutation"},
        {"name": "Otiluke's Freezing Sphere", "school": "Evocation"},
        {"name": "Otto's Irresistible Dance", "school": "Enchantment"},
        {"name": "Planar Ally", "school": "Conjuration"},
        {"name": "Summon Fiend", "school": "Conjuration"},
        {"name": "Sunbeam", "school": "Evocation"},
        {"name": "True Seeing", "school": "Divination"},
        {"name": "Wall Of Ice", "school": "Evocation"},
        {"name": "Wall Of Thorns", "school": "Conjuration"},
        {"name": "Wind Walk", "school": "Transmutation"},
    ],
}

magic_items = {
    "common": {
        "Armor": ["Breastplate", "Chain Mail", "Chain Shirt", "Half Plate Armor", "Hide Armor",
                  "Leather Armor", "Padded Armor", "Plate Armor", "Ring Mail",
                  "Scale Mail", "Shield", "Splint Armor", "Studded Leather Armor"],
        "Potion": ["Potion of Climbing", "Potion Of Healing"],
        "Ring": ["Ring"],
        "Rod": ["Rod"],
        "Scroll": ["Spell Scroll Cantrip Acid Splash", "Spell Scroll Cantrip Blade Ward",
                   "Spell Scroll Cantrip Chill Touch", "Spell Scroll Cantrip Eldritch Blast",
                   "Spell Scroll Cantrip Fire Bolt", "Spell Scroll Cantrip Guidance",
                   "Spell Scroll Cantrip Light", "Spell Scroll Cantrip Mending",
                   "Spell Scroll Cantrip Mind Sliver", "Spell Scroll Cantrip Poison Spray",
                   "Spell Scroll Cantrip Produce Flame", "Spell Scroll Cantrip Ray Of Frost",
                   "Spell Scroll Cantrip Resistance", "Spell Scroll Cantrip Sacred Flame",
                   "Spell Scroll Cantrip Shillelagh", "Spell Scroll Cantrip Shocking Grasp",
                   "Spell Scroll Cantrip Sourcerous Burst", "Spell Scroll Cantrip Spare The Dying",
                   "Spell Scroll Cantrip Starry Wisp", "Spell Scroll Cantrip Thorn Whip",
                   "Spell Scroll Cantrip Thunderclap", "Spell Scroll Cantrip Toll The Dead",
                   "Spell Scroll Cantrip True Strike", "Spell Scroll Cantrip Vicious Mockery",
                   "Spell Scroll Cantrip Word Of Radiance", "Spell Scroll 1st Level Alarm",
                   "Spell Scroll 1st Level Armor Of Agathys", "Spell Scroll 1st Level Arms Of Hadar",
                   "Spell Scroll 1st Level Bane", "Spell Scroll 1st Level Bless",
                   "Spell Scroll 1st Level Burning Hands", "Spell Scroll 1st Level Charm Person",
                   "Spell Scroll 1st Level Chromatic Orb", "Spell Scroll 1st Level Color Spray",
                   "Spell Scroll 1st Level Command", "Spell Scroll 1st Level Compelled Duel",
                   "Spell Scroll 1st Level Cure Wounds", "Spell Scroll 1st Level Detect Evil And Good",
                   "Spell Scroll 1st Level Detect Magic", "Spell Scroll 1st Level Detect Poison And Disease",
                   "Spell Scroll 1st Level Dissonant Whispers", "Spell Scroll 1st Level Divine Favor",
                   "Spell Scroll 1st Level Divine Smite", "Spell Scroll 1st Level Ensnaring Strike",
                   "Spell Scroll 1st Level Entangle", "Spell Scroll 1st Level Expeditious Retreat",
                   "Spell Scroll 1st Level Faerie Fire", "Spell Scroll 1st Level False Life",
                   "Spell Scroll 1st Level Feather Fall", "Spell Scroll 1st Level Find Familiar",
                   "Spell Scroll 1st Level Fog Cloud", "Spell Scroll 1st Level Goodberry",
                   "Spell Scroll 1st Level Grease", "Spell Scroll 1st Level Guiding Bolt",
                   "Spell Scroll 1st Level Hail Of Thorns", "Spell Scroll 1st Level Healing Word",
                   "Spell Scroll 1st Level Hellish Rebuke", "Spell Scroll 1st Level Heroism",
                   "Spell Scroll 1st Level Hex", "Spell Scroll 1st Level Hunter's Mark",
                   "Spell Scroll 1st Level Ice Knife", "Spell Scroll 1st Level Inflict Wounds",
                   "Spell Scroll 1st Level Jump", "Spell Scroll 1st Level Longstrider",
                   "Spell Scroll 1st Level Mage Armor", "Spell Scroll 1st Level Magic Missile",
                   "Spell Scroll 1st Level Protection From Evil And Good", "Spell Scroll 1st Level Ray Of Sickness",
                   "Spell Scroll 1st Level Sanctuary", "Spell Scroll 1st Level Searing Smite",
                   "Spell Scroll 1st Level Shield", "Spell Scroll 1st Level Shield Of Faith",
                   "Spell Scroll 1st Level Sleep", "Spell Scroll 1st Level Tasha's Hideous Laughter",
                   "Spell Scroll 1st Level Thunderous Smite", "Spell Scroll 1st Level Thunderwave",
                   "Spell Scroll 1st Level Witch Bolt", "Spell Scroll 1st Level Wrathful Smite"],
        "Staff": ["Staff"],
        "Wand": ["Wand"],
        "Weapon": ["Battleaxe", "Club", "Dagger", "Flail", "Glaive", "Greataxe", "Greatclub",
                   "Halberd", "Hand Crossbow", "Handaxe", "Heavy Crossbow", "Javelin", "Lance",
                   "Light Crossbow", "Light Hammer", "Longbow", "Longsword", "Mace", "Maul", "Morningstar",
                   "Musket", "Pike", "Pistol", "Quarterstaff", "Rapier", "Scimitar", "Shortbow", "Shortsword",
                   "Sickle", "Sling", "Spear", "Trident", "War Pick", "Warhammer", "Whip", "Wooden Staff"],
    },
    "uncommon": {
        "Armor": ["Adamantine Breastplate", "Adamantine Chain Mail", "Adamantine Half Plate Armor",
                  "Adamantine Plate Armor", "Adamantine Ring Mail", "Adamantine Scale Mail", "Adamantine Splint Armor",
                  ""],
        "Potion": ["Scroll of Protection"],
        "Ring": ["Mithral Armor"],
        "Rod": ["Ring of Water Walking"],
        "Scroll": ["Rod of the Pact Keeper +1"],
        "Staff": ["Staff of the Adder"],
        "Wand": ["Wand of Magic Missiles"],
        "Weapon": ["+1 Longsword"]
    },
    "rare": {
        "Potion": ["Potion of Superior Healing"],
        "Scroll": ["Scroll of Fireball"],
        "Armor": ["Adamantine Armor"],
        "Ring": ["Ring of Evasion"],
        "Rod": ["Rod of Absorption"],
        "Staff": ["Staff of Fire"],
        "Wand": ["Wand of Paralysis"],
        "Weapon": ["+2 Longsword"]
    },
    "very rare": {
        "Potion": ["Potion of Invisibility"],
        "Scroll": ["Scroll of Wall of Force"],
        "Armor": ["Armor of Invulnerability"],
        "Ring": ["Ring of Regeneration"],
        "Rod": ["Rod of Lordly Might"],
        "Staff": ["Staff of Power"],
        "Wand": ["Wand of Wonder"],
        "Weapon": ["Holy Avenger"]
    },
    "legendary": {
        "Potion": ["Potion of Storm Giant Strength"],
        "Scroll": ["Scroll of Meteor Swarm"],
        "Armor": ["Plate Armor of Etherealness"],
        "Ring": ["Ring of Three Wishes"],
        "Rod": ["Rod of Resurrection"],
        "Staff": ["Staff of the Magi"],
        "Wand": ["Wand of Orcus"],
        "Weapon": ["Vorpal Sword"]
    }
}

def get_rations():
    roll = random.randint(1, 10)
    if roll <= 5:
        return 0
    elif roll <= 9:
        return 1
    else:
        return 2

def generate_encounter(encounter_number):
    if encounter_number == 1:
        encounter = {
            "monsters": random.sample(monsters["1/2"], 2) + random.sample(monsters["1/4"], 2),
            "xp": 600,
            "gold": 100,
            "magic_items": random.sample(magic_items["common"] + magic_items["uncommon"], 4),
            "rations": get_rations()
        }
        return encounter

encounter = generate_encounter(1)
for key, value in encounter.items():
    print(f"{key.capitalize()}: {value}")