"""Add auto save generated runs preference

Revision ID: 08105591dfef
Revises: dc1b63db0fc1
Create Date: 2026-08-16 10:56:21.668634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08105591dfef'
down_revision = 'dc1b63db0fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_save_generated_runs', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_save_generated_runs')

    # ### end Alembic commands ###
