"""add_discord_id_and_recovery_code

Revision ID: 0da48c2cad39
Revises: 249cdbd4ecdd
Create Date: 2026-05-30 12:24:39.142298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da48c2cad39'
down_revision = '249cdbd4ecdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('code_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('security_answer_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_answer_encrypted', sa.TEXT(), nullable=True))
        batch_op.drop_column('discord_id')

    with op.batch_alter_table('recovery_request', schema=None) as batch_op:
        batch_op.drop_column('code_expires_at')
        batch_op.drop_column('recovery_code')

    # ### end Alembic commands ###
