"""Add pending_rest to SessionParticipant

Revision ID: 17683758e420
Revises: b0f4c8d9a123
Create Date: 2026-06-03 21:24:33.985220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17683758e420'
down_revision = 'b0f4c8d9a123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_rest', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_participant', schema=None) as batch_op:
        batch_op.drop_column('pending_rest')

    # ### end Alembic commands ###
