"""Add recovery system

Revision ID: 249cdbd4ecdd
Revises: ff1575293277
Create Date: 2026-05-15 11:07:51.875942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249cdbd4ecdd'
down_revision = 'ff1575293277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_answer_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_answer_encrypted')

    # ### end Alembic commands ###
