"""Add patreon OAuth fields

Revision ID: c04e1aecb332
Revises: dd35389df158
Create Date: 2026-08-11 19:56:20.424657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04e1aecb332'
down_revision = 'dd35389df158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patreon_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patreon_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patreon_last_checked', sa.DateTime(), nullable=True))
        batch_op.alter_column('patreon_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('patreon_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('patreon_last_checked')
        batch_op.drop_column('patreon_refresh_token')
        batch_op.drop_column('patreon_access_token')

    # ### end Alembic commands ###
