"""Add daily run generation limit fields

Revision ID: dc1b63db0fc1
Revises: c04e1aecb332
Create Date: 2026-08-13 17:49:36.255411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1b63db0fc1'
down_revision = 'c04e1aecb332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'run_generations_today',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )
        batch_op.add_column(sa.Column('run_generation_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('run_generation_date')
        batch_op.drop_column('run_generations_today')

    # ### end Alembic commands ###
