"""Add Patreon support fields

Revision ID: dd35389df158
Revises: 17683758e420
Create Date: 2026-06-25 15:07:07.469150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd35389df158'
down_revision = '17683758e420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patreon_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('patreon_connected', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('patreon_tier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('patreon_tier')
        batch_op.drop_column('patreon_connected')
        batch_op.drop_column('patreon_id')

    # ### end Alembic commands ###
